# Site Settings - 1열
locale: "ko-KR"
title: "권하일 / 프로젝트 포트폴리오"
name: &name "권하일"
description: &description "한신대학교 AI.SW학과 학생의 학업 및 프로젝트 포트폴리오"
url: https://inko1122.github.io
baseurl: ""
repository: "inko1122/[당신의_저장소_이름]"

# Site Author - 1열
author:
  # Biographic information
  avatar: "profile.png"
  name: "권하일"
  bio: "한신대학교 AI.SW학과 202578152 학번 권하일입니다!"
  location: "South Korea/ Gyeonggi/Dongtan"
  employer: "Hanshin University"
  uri: "https://www.hanshin.ac.kr"
  email: "gkdlf56890@naver.com"
  # Repositories and software development
  github: "inko1122"

# Collections - 1열
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/